### ISSUE TITLE
Overview on STIX/TAXII & History - 0.5 hours of content

### ISSUE THREAD

**Issue by treyka** [oasis-open/cti-training#1]
Review and update this portion of the slide deck

**Comment by treyka** [comment]
Here's the current Google Docs preso: https://docs.google.com/presentation/d/1zB9dxNyybs3JJU30CGvINhqdKljvH8WhtDtRSGzoQrY/edit?usp=sharing

**Comment by ikiril01** [comment]
I'm assuming Rich Struse is presenting this.
