### ISSUE TITLE
STIX2 Data Model Foundations - 2.5 hours of content

### ISSUE THREAD

**Issue by treyka** [oasis-open/cti-training#2]
* Use Cases supported (~10 min)
* Overall architecture (~20 min)
* Working with objects and how to construct related intelligence (~30 min)
* Object versioning (~10 min)
* Customization and extension (~10 min)
* Pattern language introduction and examples (~20 min)
* Interop implications integrated throughout (?)

**Comment by ikiril01** [comment]
I believe we already have some slides we can use for (at least as a starting point):

* Overall architecture
* Working with objects and how to construct related intelligence
* Pattern language introduction and examples

**Comment by ikiril01** [comment]
We should also try to break down each topic by time, to give us a rough idea of how much content we'll need - I took a stab at doing so in the top comment

**Comment by JG-CTIN** [comment]
![stix2_scos](https://user-images.githubusercontent.com/14005876/39582965-e9cb53e8-4ea3-11e8-938f-f3c38ec7f776.PNG)
Here is a figure that you can use.
Citation:  https://www.eclecticiq.com/resources/eclecticiq-white-paper-using-a-robust-platform-for-training-purposes

**Comment by JG-CTIN** [comment]
![idealized_tip_eiq](https://user-images.githubusercontent.com/14005876/39583147-4ace415a-4ea4-11e8-8fcb-01bfb938c707.PNG)
Citation: https://www.eclecticiq.com/resources/eclecticiq-white-paper-using-a-robust-platform-for-training-purposes

**Comment by ikiril01** [comment]
Deck: https://docs.google.com/presentation/d/155XKQGdaHLEl2pEmEV6QG0IXf0bJxk6vIJ2AuQ8ODWk/edit?usp=sharing

**Comment by ikiril01** [comment]
We should also discuss the new stuff in STIX 2.1 CSD01.

**Comment by treyka** [comment]
My thought on the "Working with objects and how to construct related intelligence" item was that we'd hand out the EclecticIQ card decks and we'd guide people through playing with them.

**Comment by ikiril01** [comment]
The other question is how do we divide this up during the presentation? Who's presenting what?
